### ISSUE TITLE
貌似后台有一个问题

### ISSUE THREAD

**Issue by Ztiany** [xitu/xitu.github.io#2]
我喜欢的界面，显示有七条数据，进去之后却没有内容。

网页：
![qq 20170228142435](https://cloud.githubusercontent.com/assets/8726426/23394081/f7c5ae0a-fdc1-11e6-872c-4f88501c1fd4.png)
Android端,Item无法点进去：
![screenshot_2017-02-28-14-25-09-496_com daimajia g](https://cloud.githubusercontent.com/assets/8726426/23394093/fe24c024-fdc1-11e6-8db7-112bea1cdb90.png)

**Comment by kalasoo** [comment]
收到反馈

**Comment by kalasoo** [comment]
已经修复，是您之前收藏的文章数据被删除了导致的

**Comment by Ztiany** [comment]
好的，真是迅速。
